version: "3"

volumes:
  geo-db-data:

services:
  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - 65432:5432
    env_file:
      - docker-env/db.env
    restart: on-failure
    healthcheck:
      test: "exit 0"

  geoserver:
    image: camptocamp/geoserver:jetty-2.15.0
    volumes:
      - ./app/server/geoserver/data_dir:/mnt/geoserver_datadir
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db

  api:
    build:
      context: ./app/server/api
      dockerfile: ./Dockerfile
    volumes:
      - ./app/server/api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:80

  print:
    image: camptocamp/mapfish_print:3.18
    volumes:
      - ./app/server/mapfishprint:/usr/local/tomcat/webapps/ROOT/print-apps
    ports:
      - 8585:8080

  client:
    build:
      context: ./app/client
      dockerfile: ./Dockerfile
    volumes:
      - ./app/client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:80
      
  # nginx-proxy:
  #   image: nginx:latest
  #   container_name: reverseproxy
  #   volumes:
  #     - ./app/server/reverseproxy/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 3000:80
